// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as HomeScreen from "./HomeScreen.bs.js";
import * as ReactNative from "react-native";
import * as DetailsScreen from "./DetailsScreen.bs.js";
import * as Stack$ReactNavigation from "rescript-react-navigation/src/Stack.bs.js";
import * as Native from "@react-navigation/native";

var include = Stack$ReactNavigation.Make({});

var $$Screen = include.$$Screen;

var $$Navigator = include.$$Navigator;

function App$app(Props) {
  return React.createElement(ReactNative.SafeAreaView, {
              children: null
            }, React.createElement(ReactNative.StatusBar, {}), React.createElement(Native.NavigationContainer, {
                  children: React.createElement($$Navigator.make, {
                        children: null
                      }, React.createElement($$Screen.make, {
                            name: "Main",
                            component: HomeScreen.make
                          }), React.createElement($$Screen.make, {
                            name: "Details",
                            component: DetailsScreen.make
                          }))
                }));
}

var Navigation = include.Navigation;

var HeaderTitle = include.HeaderTitle;

var Header = include.Header;

var stack = include.stack;

var ScreenWithCallback = include.ScreenWithCallback;

var app = App$app;

export {
  Navigation ,
  HeaderTitle ,
  Header ,
  stack ,
  ScreenWithCallback ,
  $$Screen ,
  $$Navigator ,
  app ,
  
}
/* include Not a pure module */
