// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";

function HomeScreen(Props) {
  return React.createElement(ReactNative.View, {
              children: React.createElement(ReactNative.Text, {
                    children: "Home screen"
                  })
            });
}

var make = HomeScreen;

export {
  make ,
  
}
/* react Not a pure module */
